# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_DoctorDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1150, 824)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1150, 805))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    \n"
"\n"
"    font: 900 16pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NavBar = QtWidgets.QWidget(self.centralwidget)
        self.NavBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setMinimumSize(QtCore.QSize(0, 0))
        self.NavBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NavBar.setAutoFillBackground(False)
        self.NavBar.setStyleSheet("")
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DashboardButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton_2.setStyleSheet("QPushButton {\n"
"    padding: 10px 8px;\n"
"}")
        self.DashboardButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lucide/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton_2.setIcon(icon)
        self.DashboardButton_2.setIconSize(QtCore.QSize(35, 35))
        self.DashboardButton_2.setObjectName("DashboardButton_2")
        self.verticalLayout.addWidget(self.DashboardButton_2)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/lucide/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons.addWidget(self.DashboardButton)
        self.StaffsButton = QtWidgets.QPushButton(self.NavBar)
        self.StaffsButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StaffsButton.setIcon(icon2)
        self.StaffsButton.setIconSize(QtCore.QSize(40, 40))
        self.StaffsButton.setObjectName("StaffsButton")
        self.MainButtons.addWidget(self.StaffsButton)
        self.PatientsButton = QtWidgets.QPushButton(self.NavBar)
        self.PatientsButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lucide/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PatientsButton.setIcon(icon3)
        self.PatientsButton.setIconSize(QtCore.QSize(40, 40))
        self.PatientsButton.setObjectName("PatientsButton")
        self.MainButtons.addWidget(self.PatientsButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        self.TransactionsButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lucide/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon4)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons.addWidget(self.TransactionsButton)
        self.ChargesButton = QtWidgets.QPushButton(self.NavBar)
        self.ChargesButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/lucide/icons/hand-coins.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChargesButton.setIcon(icon5)
        self.ChargesButton.setIconSize(QtCore.QSize(40, 40))
        self.ChargesButton.setObjectName("ChargesButton")
        self.MainButtons.addWidget(self.ChargesButton)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.SettingButtons = QtWidgets.QVBoxLayout()
        self.SettingButtons.setSpacing(15)
        self.SettingButtons.setObjectName("SettingButtons")
        self.ProfileButton = QtWidgets.QPushButton(self.NavBar)
        self.ProfileButton.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProfileButton.setIcon(icon6)
        self.ProfileButton.setIconSize(QtCore.QSize(40, 40))
        self.ProfileButton.setObjectName("ProfileButton")
        self.SettingButtons.addWidget(self.ProfileButton)
        self.LogOutButton = QtWidgets.QPushButton(self.NavBar)
        self.LogOutButton.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/lucide/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogOutButton.setIcon(icon7)
        self.LogOutButton.setIconSize(QtCore.QSize(40, 40))
        self.LogOutButton.setObjectName("LogOutButton")
        self.SettingButtons.addWidget(self.LogOutButton, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.SettingButtons)
        self.horizontalLayout_4.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(self.centralwidget)
        self.MainBodyContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 80))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackButtonCon = QtWidgets.QWidget(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackButtonCon.sizePolicy().hasHeightForWidth())
        self.BackButtonCon.setSizePolicy(sizePolicy)
        self.BackButtonCon.setMinimumSize(QtCore.QSize(0, 50))
        self.BackButtonCon.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BackButtonCon.setStyleSheet("#Title{\n"
"    font: 700 12pt \"Lexend\";\n"
"}\n"
"#Subtitle {\n"
"    font: 300 8pt \"Lexend Light\";\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    text-align: left;\n"
"}\n"
"")
        self.BackButtonCon.setObjectName("BackButtonCon")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BackButtonCon)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackButton = QtWidgets.QPushButton(self.BackButtonCon)
        self.BackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BackButton.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: #2E6E65;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}")
        self.BackButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/lucide/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon8)
        self.BackButton.setIconSize(QtCore.QSize(40, 40))
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout.addWidget(self.BackButton)
        self.widget = QtWidgets.QWidget(self.BackButtonCon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Subtitle = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Subtitle.sizePolicy().hasHeightForWidth())
        self.Subtitle.setSizePolicy(sizePolicy)
        self.Subtitle.setMinimumSize(QtCore.QSize(0, 0))
        self.Subtitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Subtitle.setObjectName("Subtitle")
        self.verticalLayout_5.addWidget(self.Subtitle, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(0, 0))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setAlignment(QtCore.Qt.AlignLeading)
        self.Title.setWordWrap(True)
        self.Title.setObjectName("Title")
        self.verticalLayout_5.addWidget(self.Title, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.BackButtonCon, 0, QtCore.Qt.AlignTop)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_3.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 9px; \n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E0E0E0;  \n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #CCE3D0;\n"
"    color: #2E6E65;\n"
"}\n"
"")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_4.setContentsMargins(20, 0, 20, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLayout = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLayout.sizePolicy().hasHeightForWidth())
        self.BodyLayout.setSizePolicy(sizePolicy)
        self.BodyLayout.setObjectName("BodyLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BodyLayout)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DoctorDetails = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoctorDetails.sizePolicy().hasHeightForWidth())
        self.DoctorDetails.setSizePolicy(sizePolicy)
        self.DoctorDetails.setMinimumSize(QtCore.QSize(330, 0))
        self.DoctorDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DoctorDetails.setStyleSheet("QLabel {\n"
"    font: 10pt \"Lexend\";\n"
"    color: #2B3752;\n"
"}\n"
"#DoctorDetails {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"Line {\n"
"    background-color: #2E6E65;\n"
"    height: 2px;\n"
"}\n"
"QGraphicsView {\n"
"    border-radius: 10px;\n"
"    background: white; \n"
"}\n"
"#DocID, #DocSpecialty, #DocAge, #DocAbout, #DocContact, #DocEmail, #DocAddress {\n"
"    font: 500 13pt \"Lexend\";\n"
"}\n"
"#DocName {\n"
"    font: 700 17pt \"Lexend\";\n"
"}\n"
"#DocAvailability {\n"
"    font: 12pt \"Lexend\";\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    padding: 5px 5px;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"")
        self.DoctorDetails.setObjectName("DoctorDetails")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DoctorDetails)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Basics = QtWidgets.QWidget(self.DoctorDetails)
        self.Basics.setObjectName("Basics")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Basics)
        self.verticalLayout_7.setContentsMargins(20, 35, 20, 0)
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DocProfile = QtWidgets.QGraphicsView(self.Basics)
        self.DocProfile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocProfile.sizePolicy().hasHeightForWidth())
        self.DocProfile.setSizePolicy(sizePolicy)
        self.DocProfile.setMinimumSize(QtCore.QSize(100, 100))
        self.DocProfile.setMaximumSize(QtCore.QSize(100, 100))
        self.DocProfile.setObjectName("DocProfile")
        self.verticalLayout_7.addWidget(self.DocProfile, 0, QtCore.Qt.AlignHCenter)
        self.widget_14 = QtWidgets.QWidget(self.Basics)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.DocName = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Lexend")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.DocName.setFont(font)
        self.DocName.setAlignment(QtCore.Qt.AlignLeading)
        self.DocName.setObjectName("DocName")
        self.verticalLayout_13.addWidget(self.DocName, 0, QtCore.Qt.AlignHCenter)
        self.DocID = QtWidgets.QLabel(self.widget_14)
        self.DocID.setAlignment(QtCore.Qt.AlignLeading)
        self.DocID.setObjectName("DocID")
        self.verticalLayout_13.addWidget(self.DocID, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.widget_14)
        self.verticalLayout_6.addWidget(self.Basics)
        self.line = QtWidgets.QFrame(self.DoctorDetails)
        self.line.setEnabled(True)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setStyleSheet("Line {\n"
"    background-color: #2E6E65;\n"
"    height: 2px;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.GenInfo = QtWidgets.QWidget(self.DoctorDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GenInfo.sizePolicy().hasHeightForWidth())
        self.GenInfo.setSizePolicy(sizePolicy)
        self.GenInfo.setObjectName("GenInfo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.GenInfo)
        self.verticalLayout_8.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_8.setSpacing(30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_8 = QtWidgets.QWidget(self.GenInfo)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.widget_9)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.DocSpecialty = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocSpecialty.sizePolicy().hasHeightForWidth())
        self.DocSpecialty.setSizePolicy(sizePolicy)
        self.DocSpecialty.setWordWrap(True)
        self.DocSpecialty.setObjectName("DocSpecialty")
        self.verticalLayout_10.addWidget(self.DocSpecialty)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_9.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.widget_10)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.DocAge = QtWidgets.QLabel(self.widget_10)
        self.DocAge.setObjectName("DocAge")
        self.verticalLayout_9.addWidget(self.DocAge)
        self.horizontalLayout_5.addWidget(self.widget_10)
        self.verticalLayout_8.addWidget(self.widget_8, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.GenInfo)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.DocAbout = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocAbout.sizePolicy().hasHeightForWidth())
        self.DocAbout.setSizePolicy(sizePolicy)
        self.DocAbout.setObjectName("DocAbout")
        self.verticalLayout_11.addWidget(self.DocAbout)
        self.verticalLayout_8.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.GenInfo, 0, QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.DoctorDetails)
        self.line_2.setStyleSheet("Line {\n"
"    background-color: #2E6E65;\n"
"    height: 2px;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.Contacts = QtWidgets.QWidget(self.DoctorDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contacts.sizePolicy().hasHeightForWidth())
        self.Contacts.setSizePolicy(sizePolicy)
        self.Contacts.setObjectName("Contacts")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Contacts)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 20)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_11 = QtWidgets.QWidget(self.Contacts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.widget_11)
        self.pushButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/lucide/icons/phone.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.DocContact = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocContact.sizePolicy().hasHeightForWidth())
        self.DocContact.setSizePolicy(sizePolicy)
        self.DocContact.setAlignment(QtCore.Qt.AlignLeading)
        self.DocContact.setObjectName("DocContact")
        self.horizontalLayout_6.addWidget(self.DocContact, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_12.addWidget(self.widget_11, 0, QtCore.Qt.AlignTop)
        self.widget_12 = QtWidgets.QWidget(self.Contacts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/lucide/icons/mail.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignLeft)
        self.DocEmail = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocEmail.sizePolicy().hasHeightForWidth())
        self.DocEmail.setSizePolicy(sizePolicy)
        self.DocEmail.setAlignment(QtCore.Qt.AlignLeading)
        self.DocEmail.setWordWrap(True)
        self.DocEmail.setObjectName("DocEmail")
        self.horizontalLayout_7.addWidget(self.DocEmail, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_12.addWidget(self.widget_12, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget_13 = QtWidgets.QWidget(self.Contacts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/lucide/icons/house.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon11)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignLeft)
        self.DocAddress = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DocAddress.sizePolicy().hasHeightForWidth())
        self.DocAddress.setSizePolicy(sizePolicy)
        self.DocAddress.setAlignment(QtCore.Qt.AlignLeading)
        self.DocAddress.setWordWrap(True)
        self.DocAddress.setObjectName("DocAddress")
        self.horizontalLayout_8.addWidget(self.DocAddress, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_12.addWidget(self.widget_13, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.Contacts)
        self.horizontalLayout_2.addWidget(self.DoctorDetails, 0, QtCore.Qt.AlignTop)
        self.widget_3 = QtWidgets.QWidget(self.BodyLayout)
        self.widget_3.setMinimumSize(QtCore.QSize(260, 0))
        self.widget_3.setStyleSheet("#PatOverview {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"#CategoryLine, #CategoryLine_2,  #CategoryLine_3 {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    border-radius: 12px\n"
"}\n"
"#Category, #Category_2, #Percentage, #Percentage_2 {\n"
"    color: #2B3752;\n"
"} \n"
"#OverviewSub, #OverviewSub_2 {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 22px;\n"
"    background: white;\n"
"}\n"
"#DoctorName, #PatientCount {\n"
"    color: #2B3752;\n"
"    font: 500 13pt \"Lexend\";\n"
"}\n"
"#Specialty, #PatientPercentage {\n"
"    font: 10pt \"Lexend\";\n"
"    color: #2B3752;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.PatOverview = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatOverview.sizePolicy().hasHeightForWidth())
        self.PatOverview.setSizePolicy(sizePolicy)
        self.PatOverview.setMinimumSize(QtCore.QSize(259, 0))
        self.PatOverview.setMaximumSize(QtCore.QSize(400, 16777215))
        self.PatOverview.setObjectName("PatOverview")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.PatOverview)
        self.verticalLayout_21.setContentsMargins(10, 10, 10, 20)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_15 = QtWidgets.QWidget(self.PatOverview)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.DashboardButton_9 = QtWidgets.QPushButton(self.widget_15)
        self.DashboardButton_9.setStyleSheet("")
        self.DashboardButton_9.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/lucide/icons/chart-bar-big.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton_9.setIcon(icon12)
        self.DashboardButton_9.setIconSize(QtCore.QSize(35, 35))
        self.DashboardButton_9.setObjectName("DashboardButton_9")
        self.horizontalLayout_25.addWidget(self.DashboardButton_9, 0, QtCore.Qt.AlignTop)
        self.widget_16 = QtWidgets.QWidget(self.widget_15)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.OverviewHeader_3 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OverviewHeader_3.sizePolicy().hasHeightForWidth())
        self.OverviewHeader_3.setSizePolicy(sizePolicy)
        self.OverviewHeader_3.setAlignment(QtCore.Qt.AlignLeading)
        self.OverviewHeader_3.setObjectName("OverviewHeader_3")
        self.verticalLayout_22.addWidget(self.OverviewHeader_3, 0, QtCore.Qt.AlignTop)
        self.OverviewSub_2 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OverviewSub_2.sizePolicy().hasHeightForWidth())
        self.OverviewSub_2.setSizePolicy(sizePolicy)
        self.OverviewSub_2.setAlignment(QtCore.Qt.AlignLeading)
        self.OverviewSub_2.setObjectName("OverviewSub_2")
        self.verticalLayout_22.addWidget(self.OverviewSub_2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_25.addWidget(self.widget_16, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_21.addWidget(self.widget_15, 0, QtCore.Qt.AlignTop)
        self.CategoryCon_3 = QtWidgets.QWidget(self.PatOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoryCon_3.sizePolicy().hasHeightForWidth())
        self.CategoryCon_3.setSizePolicy(sizePolicy)
        self.CategoryCon_3.setObjectName("CategoryCon_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.CategoryCon_3)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.CategoryLine_3 = QtWidgets.QWidget(self.CategoryCon_3)
        self.CategoryLine_3.setObjectName("CategoryLine_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.CategoryLine_3)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Category_2 = QtWidgets.QLabel(self.CategoryLine_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Category_2.sizePolicy().hasHeightForWidth())
        self.Category_2.setSizePolicy(sizePolicy)
        self.Category_2.setAlignment(QtCore.Qt.AlignLeading)
        self.Category_2.setObjectName("Category_2")
        self.horizontalLayout_26.addWidget(self.Category_2)
        self.Percentage_2 = QtWidgets.QLabel(self.CategoryLine_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Percentage_2.sizePolicy().hasHeightForWidth())
        self.Percentage_2.setSizePolicy(sizePolicy)
        self.Percentage_2.setAlignment(QtCore.Qt.AlignLeading)
        self.Percentage_2.setObjectName("Percentage_2")
        self.horizontalLayout_26.addWidget(self.Percentage_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_23.addWidget(self.CategoryLine_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_21.addWidget(self.CategoryCon_3)
        self.verticalLayout_14.addWidget(self.PatOverview)
        self.horizontalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(280, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.NotificationBox = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotificationBox.sizePolicy().hasHeightForWidth())
        self.NotificationBox.setSizePolicy(sizePolicy)
        self.NotificationBox.setMinimumSize(QtCore.QSize(280, 0))
        self.NotificationBox.setMaximumSize(QtCore.QSize(280, 16777215))
        self.NotificationBox.setStyleSheet("#NotificationBox{\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"#NotifObject{\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#NotificationLabel {\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 22px;\n"
"    background: white;\n"
"}\n"
"\n"
"#NotifTimestamp {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 14px;\n"
"    color: #2B3752;\n"
"}\n"
"\n"
"#NotifDescription {\n"
"    font: 10pt \"Lexend\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}")
        self.NotificationBox.setObjectName("NotificationBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.NotificationBox)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 20)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.NotificationLabel = QtWidgets.QLabel(self.NotificationBox)
        self.NotificationLabel.setStyleSheet("")
        self.NotificationLabel.setObjectName("NotificationLabel")
        self.verticalLayout_15.addWidget(self.NotificationLabel, 0, QtCore.Qt.AlignTop)
        self.Notifications = QtWidgets.QWidget(self.NotificationBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Notifications.sizePolicy().hasHeightForWidth())
        self.Notifications.setSizePolicy(sizePolicy)
        self.Notifications.setObjectName("Notifications")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Notifications)
        self.verticalLayout_16.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.NotifObject = QtWidgets.QWidget(self.Notifications)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotifObject.sizePolicy().hasHeightForWidth())
        self.NotifObject.setSizePolicy(sizePolicy)
        self.NotifObject.setMinimumSize(QtCore.QSize(0, 0))
        self.NotifObject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NotifObject.setObjectName("NotifObject")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.NotifObject)
        self.horizontalLayout_9.setContentsMargins(10, 5, 10, 4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.NotifDetails = QtWidgets.QWidget(self.NotifObject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotifDetails.sizePolicy().hasHeightForWidth())
        self.NotifDetails.setSizePolicy(sizePolicy)
        self.NotifDetails.setMinimumSize(QtCore.QSize(0, 0))
        self.NotifDetails.setObjectName("NotifDetails")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.NotifDetails)
        self.verticalLayout_17.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.NotifDescription = QtWidgets.QLabel(self.NotifDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotifDescription.sizePolicy().hasHeightForWidth())
        self.NotifDescription.setSizePolicy(sizePolicy)
        self.NotifDescription.setAlignment(QtCore.Qt.AlignLeading)
        self.NotifDescription.setObjectName("NotifDescription")
        self.verticalLayout_17.addWidget(self.NotifDescription, 0, QtCore.Qt.AlignTop)
        self.NotifTimestamp = QtWidgets.QLabel(self.NotifDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotifTimestamp.sizePolicy().hasHeightForWidth())
        self.NotifTimestamp.setSizePolicy(sizePolicy)
        self.NotifTimestamp.setMinimumSize(QtCore.QSize(0, 0))
        self.NotifTimestamp.setAlignment(QtCore.Qt.AlignLeading)
        self.NotifTimestamp.setObjectName("NotifTimestamp")
        self.verticalLayout_17.addWidget(self.NotifTimestamp, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_9.addWidget(self.NotifDetails)
        self.verticalLayout_16.addWidget(self.NotifObject, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_15.addWidget(self.Notifications)
        self.verticalLayout_18.addWidget(self.NotificationBox)
        self.horizontalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.BodyLayout, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout_4.addWidget(self.MainBodyContainer)
        self.MainBodyContainer.raise_()
        self.NavBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DashboardButton_2.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.DashboardButton.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.DashboardButton.setText(_translate("MainWindow", "  Dashboard"))
        self.StaffsButton.setToolTip(_translate("MainWindow", "View Staff Record"))
        self.StaffsButton.setText(_translate("MainWindow", "  Staffs"))
        self.PatientsButton.setToolTip(_translate("MainWindow", "View Patient Record"))
        self.PatientsButton.setText(_translate("MainWindow", "  Records"))
        self.TransactionsButton.setToolTip(_translate("MainWindow", "View Transactions "))
        self.TransactionsButton.setText(_translate("MainWindow", "  Transactions"))
        self.ChargesButton.setToolTip(_translate("MainWindow", "View Reports and Overviews"))
        self.ChargesButton.setText(_translate("MainWindow", "  Charges"))
        self.ProfileButton.setToolTip(_translate("MainWindow", "View Profile Settings"))
        self.ProfileButton.setText(_translate("MainWindow", "  Profile"))
        self.LogOutButton.setToolTip(_translate("MainWindow", "Log Out from your Account"))
        self.LogOutButton.setText(_translate("MainWindow", "  Log Out"))
        self.Subtitle.setText(_translate("MainWindow", " Back to Doctor List"))
        self.Title.setText(_translate("MainWindow", "Doctor Details"))
        self.UserName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("MainWindow", "Admin"))
        self.DocName.setText(_translate("MainWindow", "Dr. Roy Adrian Rondina"))
        self.DocID.setText(_translate("MainWindow", "10002"))
        self.label.setText(_translate("MainWindow", "Specialty"))
        self.DocSpecialty.setText(_translate("MainWindow", "Ophthalmologist"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.DocAge.setText(_translate("MainWindow", "54"))
        self.label_5.setText(_translate("MainWindow", "Date Joined"))
        self.DocAbout.setText(_translate("MainWindow", "December 13, 2003"))
        self.DocContact.setText(_translate("MainWindow", "+63 1234 567 8910"))
        self.DocEmail.setText(_translate("MainWindow", "rondina.sample@gmail.com"))
        self.DocAddress.setText(_translate("MainWindow", "Sample Street, Pardo, Cebu City"))
        self.DashboardButton_9.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.OverviewHeader_3.setText(_translate("MainWindow", "Patient Overview"))
        self.OverviewSub_2.setText(_translate("MainWindow", "By Age Stage"))
        self.Category_2.setText(_translate("MainWindow", "Fever"))
        self.Percentage_2.setText(_translate("MainWindow", "36%"))
        self.NotificationLabel.setText(_translate("MainWindow", "Recent Activity"))
        self.NotifDescription.setText(_translate("MainWindow", "Dr. Limosnero diagnosed a patient with fever."))
        self.NotifTimestamp.setText(_translate("MainWindow", "15:22 | February 13, 2020"))
import Images.resources
