# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_PatientDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1150, 820)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1150, 805))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 16pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NavBar = QtWidgets.QWidget(self.centralwidget)
        self.NavBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setMinimumSize(QtCore.QSize(0, 0))
        self.NavBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NavBar.setAutoFillBackground(False)
        self.NavBar.setStyleSheet("")
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavBarButton = QtWidgets.QPushButton(self.NavBar)
        self.NavBarButton.setStyleSheet("QPushButton {\n"
"    padding: 10px 8px;\n"
"}")
        self.NavBarButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lucide/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NavBarButton.setIcon(icon)
        self.NavBarButton.setIconSize(QtCore.QSize(35, 35))
        self.NavBarButton.setObjectName("NavBarButton")
        self.verticalLayout.addWidget(self.NavBarButton)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/lucide/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons.addWidget(self.DashboardButton)
        self.StaffsButton = QtWidgets.QPushButton(self.NavBar)
        self.StaffsButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StaffsButton.setIcon(icon2)
        self.StaffsButton.setIconSize(QtCore.QSize(40, 40))
        self.StaffsButton.setObjectName("StaffsButton")
        self.MainButtons.addWidget(self.StaffsButton)
        self.PatientsButton = QtWidgets.QPushButton(self.NavBar)
        self.PatientsButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lucide/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PatientsButton.setIcon(icon3)
        self.PatientsButton.setIconSize(QtCore.QSize(40, 40))
        self.PatientsButton.setObjectName("PatientsButton")
        self.MainButtons.addWidget(self.PatientsButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        self.TransactionsButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lucide/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon4)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons.addWidget(self.TransactionsButton)
        self.ChargesButton = QtWidgets.QPushButton(self.NavBar)
        self.ChargesButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/lucide/icons/hand-coins.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChargesButton.setIcon(icon5)
        self.ChargesButton.setIconSize(QtCore.QSize(40, 40))
        self.ChargesButton.setObjectName("ChargesButton")
        self.MainButtons.addWidget(self.ChargesButton)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.SettingButtons = QtWidgets.QVBoxLayout()
        self.SettingButtons.setSpacing(15)
        self.SettingButtons.setObjectName("SettingButtons")
        self.ProfileButton = QtWidgets.QPushButton(self.NavBar)
        self.ProfileButton.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProfileButton.setIcon(icon6)
        self.ProfileButton.setIconSize(QtCore.QSize(40, 40))
        self.ProfileButton.setObjectName("ProfileButton")
        self.SettingButtons.addWidget(self.ProfileButton)
        self.LogOutButton = QtWidgets.QPushButton(self.NavBar)
        self.LogOutButton.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/lucide/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogOutButton.setIcon(icon7)
        self.LogOutButton.setIconSize(QtCore.QSize(40, 40))
        self.LogOutButton.setObjectName("LogOutButton")
        self.SettingButtons.addWidget(self.LogOutButton, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.SettingButtons)
        self.horizontalLayout_4.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(self.centralwidget)
        self.MainBodyContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 80))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackButtonCon = QtWidgets.QWidget(self.Header)
        self.BackButtonCon.setStyleSheet("#Title{\n"
"    font: 700 22pt \"Lexend\";\n"
"}\n"
"#Subtitle {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"")
        self.BackButtonCon.setObjectName("BackButtonCon")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BackButtonCon)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackButton = QtWidgets.QPushButton(self.BackButtonCon)
        self.BackButton.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: #2E6E65;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}")
        self.BackButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/lucide/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon8)
        self.BackButton.setIconSize(QtCore.QSize(40, 40))
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout.addWidget(self.BackButton, 0, QtCore.Qt.AlignLeft)
        self.widget = QtWidgets.QWidget(self.BackButtonCon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Subtitle = QtWidgets.QLabel(self.widget)
        self.Subtitle.setMinimumSize(QtCore.QSize(0, 15))
        self.Subtitle.setMaximumSize(QtCore.QSize(16777215, 15))
        self.Subtitle.setObjectName("Subtitle")
        self.verticalLayout_5.addWidget(self.Subtitle, 0, QtCore.Qt.AlignBottom)
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(0, 30))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setAlignment(QtCore.Qt.AlignLeading)
        self.Title.setWordWrap(True)
        self.Title.setObjectName("Title")
        self.verticalLayout_5.addWidget(self.Title)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.BackButtonCon, 0, QtCore.Qt.AlignTop)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_3.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_4.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLayout = QtWidgets.QWidget(self.Body)
        self.BodyLayout.setObjectName("BodyLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.BodyLayout)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PatBasic = QtWidgets.QWidget(self.BodyLayout)
        self.PatBasic.setMinimumSize(QtCore.QSize(0, 30))
        self.PatBasic.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PatBasic.setStyleSheet("#PatBasic {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"#PatID {\n"
"    font: 12pt \"Lexend\";\n"
"}\n"
"QLabel {\n"
"    color: #2B3752;\n"
"}")
        self.PatBasic.setObjectName("PatBasic")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.PatBasic)
        self.horizontalLayout_2.setContentsMargins(15, 5, 15, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.PatBasic)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PatName = QtWidgets.QLabel(self.widget_4)
        self.PatName.setAlignment(QtCore.Qt.AlignLeading)
        self.PatName.setObjectName("PatName")
        self.verticalLayout_7.addWidget(self.PatName, 0, QtCore.Qt.AlignBottom)
        self.PatID = QtWidgets.QLabel(self.widget_4)
        self.PatID.setAlignment(QtCore.Qt.AlignLeading)
        self.PatID.setObjectName("PatID")
        self.verticalLayout_7.addWidget(self.PatID, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.PatBasic)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(-1, -1, 15, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.EditPatientButton = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditPatientButton.sizePolicy().hasHeightForWidth())
        self.EditPatientButton.setSizePolicy(sizePolicy)
        self.EditPatientButton.setMinimumSize(QtCore.QSize(0, 45))
        self.EditPatientButton.setMaximumSize(QtCore.QSize(250, 45))
        self.EditPatientButton.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    padding: 5px 30px;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/lucide/icons/square-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditPatientButton.setIcon(icon9)
        self.EditPatientButton.setIconSize(QtCore.QSize(30, 30))
        self.EditPatientButton.setObjectName("EditPatientButton")
        self.verticalLayout_8.addWidget(self.EditPatientButton)
        self.horizontalLayout_2.addWidget(self.widget_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.PatBasic, 0, QtCore.Qt.AlignTop)
        self.PatInfo = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatInfo.sizePolicy().hasHeightForWidth())
        self.PatInfo.setSizePolicy(sizePolicy)
        self.PatInfo.setStyleSheet("#PatGenInfo, #HistoryCon {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    font: 12pt \"Lexend\";\n"
"    color: #2B3752;\n"
"}\n"
"#PatGender, #PatAge, #PatDoB, #PatContact, #PatAddress, #PatHeight, #PatWeight, #TransactionID, #Diagnosis, #TransactionDate {\n"
"    font: 500 15pt \"Lexend\";\n"
"}\n"
"#title, #title_2, #title_3 {\n"
"    font: 10pt \"Lexend\";\n"
"}\n"
"#Header_3, #Header_2 {\n"
"    color: #2E6E65;\n"
"    font: 700 15pt \"Lexend\";\n"
"}\n"
"#HistoryObject {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    border-radius: 15px;\n"
"}\n"
"Line {\n"
"    background-color: #2E6E65;\n"
"    max-height: 2px;\n"
"}\n"
"#LastRecord {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}")
        self.PatInfo.setObjectName("PatInfo")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.PatInfo)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PatGen = QtWidgets.QWidget(self.PatInfo)
        self.PatGen.setObjectName("PatGen")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.PatGen)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(5)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Header_3 = QtWidgets.QLabel(self.PatGen)
        self.Header_3.setObjectName("Header_3")
        self.verticalLayout_19.addWidget(self.Header_3, 0, QtCore.Qt.AlignTop)
        self.PatGenInfo = QtWidgets.QWidget(self.PatGen)
        self.PatGenInfo.setStyleSheet("")
        self.PatGenInfo.setObjectName("PatGenInfo")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PatGenInfo)
        self.verticalLayout_9.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.PatGenInfo)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_10.setSpacing(25)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.widget_11)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.PatGender = QtWidgets.QLabel(self.widget_11)
        self.PatGender.setObjectName("PatGender")
        self.verticalLayout_11.addWidget(self.PatGender)
        self.horizontalLayout_6.addWidget(self.widget_11, 0, QtCore.Qt.AlignTop)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.widget_12)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.PatAge = QtWidgets.QLabel(self.widget_12)
        self.PatAge.setObjectName("PatAge")
        self.verticalLayout_12.addWidget(self.PatAge)
        self.horizontalLayout_6.addWidget(self.widget_12, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_10.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_13.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.widget_10)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.PatDoB = QtWidgets.QLabel(self.widget_10)
        self.PatDoB.setObjectName("PatDoB")
        self.verticalLayout_13.addWidget(self.PatDoB)
        self.verticalLayout_10.addWidget(self.widget_10)
        self.widget_14 = QtWidgets.QWidget(self.widget_7)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_17.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_17.setSpacing(3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_6 = QtWidgets.QWidget(self.widget_14)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(30)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_16 = QtWidgets.QWidget(self.widget_6)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.widget_16)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.PatHeight = QtWidgets.QLabel(self.widget_16)
        self.PatHeight.setObjectName("PatHeight")
        self.verticalLayout_15.addWidget(self.PatHeight)
        self.horizontalLayout_8.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.widget_6)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.widget_17)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.PatWeight = QtWidgets.QLabel(self.widget_17)
        self.PatWeight.setObjectName("PatWeight")
        self.verticalLayout_16.addWidget(self.PatWeight)
        self.horizontalLayout_8.addWidget(self.widget_17)
        self.verticalLayout_17.addWidget(self.widget_6)
        self.LastRecord = QtWidgets.QLabel(self.widget_14)
        self.LastRecord.setObjectName("LastRecord")
        self.verticalLayout_17.addWidget(self.LastRecord)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.verticalLayout_9.addWidget(self.widget_7)
        self.line = QtWidgets.QFrame(self.PatGenInfo)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.widget_8 = QtWidgets.QWidget(self.PatGenInfo)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_13 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.widget_13)
        self.pushButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/lucide/icons/phone.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon10)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.PatContact = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatContact.sizePolicy().hasHeightForWidth())
        self.PatContact.setSizePolicy(sizePolicy)
        self.PatContact.setAlignment(QtCore.Qt.AlignLeading)
        self.PatContact.setObjectName("PatContact")
        self.horizontalLayout_7.addWidget(self.PatContact, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_14.addWidget(self.widget_13)
        self.widget_15 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/lucide/icons/house.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon11)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignLeft)
        self.PatAddress = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatAddress.sizePolicy().hasHeightForWidth())
        self.PatAddress.setSizePolicy(sizePolicy)
        self.PatAddress.setAlignment(QtCore.Qt.AlignLeading)
        self.PatAddress.setWordWrap(True)
        self.PatAddress.setObjectName("PatAddress")
        self.horizontalLayout_9.addWidget(self.PatAddress, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_14.addWidget(self.widget_15)
        self.verticalLayout_9.addWidget(self.widget_8, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_19.addWidget(self.PatGenInfo, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addWidget(self.PatGen, 0, QtCore.Qt.AlignTop)
        self.PatHistory = QtWidgets.QWidget(self.PatInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatHistory.sizePolicy().hasHeightForWidth())
        self.PatHistory.setSizePolicy(sizePolicy)
        self.PatHistory.setObjectName("PatHistory")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.PatHistory)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Header_2 = QtWidgets.QLabel(self.PatHistory)
        self.Header_2.setObjectName("Header_2")
        self.verticalLayout_18.addWidget(self.Header_2, 0, QtCore.Qt.AlignTop)
        self.HistoryCon = QtWidgets.QWidget(self.PatHistory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistoryCon.sizePolicy().hasHeightForWidth())
        self.HistoryCon.setSizePolicy(sizePolicy)
        self.HistoryCon.setObjectName("HistoryCon")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.HistoryCon)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.HistoryCon)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 432, 573))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.HistoryTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.HistoryTable.setStyleSheet("QTableWidget {\n"
"    background-color: #f0f0f0;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font:500 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 700 15pt \"Satoshi\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.HistoryTable.setObjectName("HistoryTable")
        self.HistoryTable.setColumnCount(3)
        self.HistoryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(2, item)
        self.HistoryTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_21.addWidget(self.HistoryTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_10.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.HistoryCon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_2.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_20.setContentsMargins(0, 50, 0, 0)
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_20.addWidget(self.pushButton_2)
        self.horizontalLayout_10.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_18.addWidget(self.HistoryCon)
        self.horizontalLayout_5.addWidget(self.PatHistory)
        self.verticalLayout_6.addWidget(self.PatInfo)
        self.verticalLayout_4.addWidget(self.BodyLayout)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout_4.addWidget(self.MainBodyContainer)
        self.MainBodyContainer.raise_()
        self.NavBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NavBarButton.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.DashboardButton.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.DashboardButton.setText(_translate("MainWindow", "  Dashboard"))
        self.StaffsButton.setToolTip(_translate("MainWindow", "View Staff Record"))
        self.StaffsButton.setText(_translate("MainWindow", "  Staffs"))
        self.PatientsButton.setToolTip(_translate("MainWindow", "View Patient Record"))
        self.PatientsButton.setText(_translate("MainWindow", "  Records"))
        self.TransactionsButton.setToolTip(_translate("MainWindow", "View Transactions "))
        self.TransactionsButton.setText(_translate("MainWindow", "  Transactions"))
        self.ChargesButton.setToolTip(_translate("MainWindow", "View Reports and Overviews"))
        self.ChargesButton.setText(_translate("MainWindow", "  Charges"))
        self.ProfileButton.setToolTip(_translate("MainWindow", "View Profile Settings"))
        self.ProfileButton.setText(_translate("MainWindow", "  Profile"))
        self.LogOutButton.setToolTip(_translate("MainWindow", "Log Out from your Account"))
        self.LogOutButton.setText(_translate("MainWindow", "  Log Out"))
        self.Subtitle.setText(_translate("MainWindow", " Back to Patient List"))
        self.Title.setText(_translate("MainWindow", "Patient Details"))
        self.UserName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("MainWindow", "Admin"))
        self.PatName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.PatID.setText(_translate("MainWindow", "100000003"))
        self.EditPatientButton.setText(_translate("MainWindow", "Edit Patient"))
        self.Header_3.setText(_translate("MainWindow", "General Information"))
        self.label.setText(_translate("MainWindow", "Gender"))
        self.PatGender.setText(_translate("MainWindow", "Male"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.PatAge.setText(_translate("MainWindow", "19"))
        self.label_5.setText(_translate("MainWindow", "Date of Birth"))
        self.PatDoB.setText(_translate("MainWindow", "December 13, 2003"))
        self.label_4.setText(_translate("MainWindow", "Height"))
        self.PatHeight.setText(_translate("MainWindow", "170 cm"))
        self.label_6.setText(_translate("MainWindow", "Weight"))
        self.PatWeight.setText(_translate("MainWindow", "60 kg"))
        self.LastRecord.setText(_translate("MainWindow", "(Last Record)"))
        self.PatContact.setText(_translate("MainWindow", "+63 1234 567 8910"))
        self.PatAddress.setText(_translate("MainWindow", "Sample Street, Pardo, Cebu City"))
        self.Header_2.setText(_translate("MainWindow", "Patient History"))
        item = self.HistoryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.HistoryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Checkup ID"))
        item = self.HistoryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        self.pushButton_2.setText(_translate("MainWindow", "View"))
import Images.resources
