# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_AddStaff.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(800, 700))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"    background-color: #F4F7ED;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setStyleSheet("QLabel {\n"
"    font: bold 20pt \"Satoshi Black\";\n"
"    color: #2E6E65;\n"
"    background: transparent;\n"
"    text-align: center;\n"
"}\n"
"#Subheader {\n"
"    font: 500 14pt \"Satoshi Medium\";\n"
"    text-align: center;\n"
"}\n"
"")
        self.Header.setObjectName("Header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Header)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QLabel(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(501, 0))
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.Title, 0, QtCore.Qt.AlignHCenter)
        self.Subheader = QtWidgets.QLabel(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Subheader.sizePolicy().hasHeightForWidth())
        self.Subheader.setSizePolicy(sizePolicy)
        self.Subheader.setMinimumSize(QtCore.QSize(500, 0))
        self.Subheader.setAlignment(QtCore.Qt.AlignCenter)
        self.Subheader.setObjectName("Subheader")
        self.verticalLayout_2.addWidget(self.Subheader, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QLabel {\n"
"    font: 300 12pt \"Lexend Light\";\n"
"    color: #2E6E65;\n"
"}\n"
"#Title_1, #Title_2, #Title_3 {\n"
"    font: 14pt \"Lexend SemiBold\";\n"
"}\n"
"#Indicator {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"#StaffTypeCon, #StaffNameCon, #StaffInfoCon, #SpecializationCon {\n"
"    background-color: transparent;\n"
"}\n"
"*{\n"
"    background-color: transparent;\n"
"}\n"
"#Body {\n"
"    background-color: rgba(46, 110, 101, 77);\n"
"    border-radius: 15px;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"    background-color: #F4F7ED;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QComboBox, QDateEdit {\n"
"    background-color: #F4F7ED;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"/* Drop-down arrow styling (QComboBox only) */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/lucide/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"/* ComboBox dropdown list view */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"/* ===== QDateEdit ===== */\n"
"QDateEdit {\n"
"    background-color: #F4F7ED;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(:/lucide/icons/calendar.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"\n"
"/* ===== QCalendarWidget Popup ===== */\n"
"QCalendarWidget {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"\n"
"/* Month & Year Navigation */\n"
"QCalendarWidget QToolButton {\n"
"    background-color: #F4F7ED;\n"
"    border: none;\n"
"    color: #2E6E65;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"    padding: 5px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_prevmonth {\n"
"    qproperty-icon: url(:/lucide/icons/chevron-left.svg);\n"
"    qproperty-iconSize: 16px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: url(:/lucide/icons/chevron-right.svg);\n"
"    qproperty-iconSize: 16px;\n"
"}\n"
"\n"
"/* Month/Year ComboBox & SpinBox */\n"
"QCalendarWidget QComboBox,\n"
"QCalendarWidget QSpinBox {\n"
"    background-color: #F4F7ED;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 6px;\n"
"    padding: 2px 6px;\n"
"    font: 300 11pt \"Lexend Light\";\n"
"    color: #2E6E65;\n"
"}\n"
"\n"
"/* Calendar Table (Dates & Grid) */\n"
"QCalendarWidget QTableView {\n"
"    background-color: #F4F7ED;\n"
"    border: none;\n"
"    selection-background-color: #2E6E65;\n"
"    font: 300 11pt \"Lexend Light\";\n"
"    gridline-color: #2E6E65;\n"
"}\n"
"\n"
"\n"
"")
        self.Body.setObjectName("Body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StaffTypeCon = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StaffTypeCon.sizePolicy().hasHeightForWidth())
        self.StaffTypeCon.setSizePolicy(sizePolicy)
        self.StaffTypeCon.setMinimumSize(QtCore.QSize(0, 55))
        self.StaffTypeCon.setObjectName("StaffTypeCon")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.StaffTypeCon)
        self.horizontalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.JoinedDate = QtWidgets.QWidget(self.StaffTypeCon)
        self.JoinedDate.setObjectName("JoinedDate")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.JoinedDate)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.JoinedDate)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.DateJoined = QtWidgets.QDateEdit(self.JoinedDate)
        self.DateJoined.setMinimumSize(QtCore.QSize(0, 35))
        self.DateJoined.setMaximumSize(QtCore.QSize(16777215, 35))
        self.DateJoined.setStyleSheet("color: black;")
        self.DateJoined.setReadOnly(False)
        self.DateJoined.setCalendarPopup(True)
        self.DateJoined.setObjectName("DateJoined")
        self.verticalLayout_4.addWidget(self.DateJoined)
        self.horizontalLayout_3.addWidget(self.JoinedDate, 0, QtCore.Qt.AlignTop)
        self.Staff = QtWidgets.QWidget(self.StaffTypeCon)
        self.Staff.setObjectName("Staff")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Staff)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.Staff)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.StaffType = QtWidgets.QComboBox(self.Staff)
        self.StaffType.setMinimumSize(QtCore.QSize(0, 35))
        self.StaffType.setMaximumSize(QtCore.QSize(16777215, 35))
        self.StaffType.setObjectName("StaffType")
        self.verticalLayout_5.addWidget(self.StaffType)
        self.horizontalLayout_3.addWidget(self.Staff, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.StaffTypeCon, 0, QtCore.Qt.AlignTop)
        self.StaffNameCon = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StaffNameCon.sizePolicy().hasHeightForWidth())
        self.StaffNameCon.setSizePolicy(sizePolicy)
        self.StaffNameCon.setObjectName("StaffNameCon")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.StaffNameCon)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Title_1 = QtWidgets.QLabel(self.StaffNameCon)
        self.Title_1.setObjectName("Title_1")
        self.verticalLayout_6.addWidget(self.Title_1, 0, QtCore.Qt.AlignTop)
        self.upper = QtWidgets.QWidget(self.StaffNameCon)
        self.upper.setObjectName("upper")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.upper)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.upper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 55))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.Fname = QtWidgets.QLineEdit(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fname.sizePolicy().hasHeightForWidth())
        self.Fname.setSizePolicy(sizePolicy)
        self.Fname.setMinimumSize(QtCore.QSize(0, 35))
        self.Fname.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Fname.setObjectName("Fname")
        self.verticalLayout_13.addWidget(self.Fname)
        self.horizontalLayout_4.addWidget(self.widget_7, 0, QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.Lname = QtWidgets.QLineEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lname.sizePolicy().hasHeightForWidth())
        self.Lname.setSizePolicy(sizePolicy)
        self.Lname.setMinimumSize(QtCore.QSize(0, 35))
        self.Lname.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Lname.setObjectName("Lname")
        self.verticalLayout_12.addWidget(self.Lname)
        self.horizontalLayout_4.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.widget_8 = QtWidgets.QWidget(self.widget_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.Mname = QtWidgets.QLineEdit(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mname.sizePolicy().hasHeightForWidth())
        self.Mname.setSizePolicy(sizePolicy)
        self.Mname.setMinimumSize(QtCore.QSize(0, 35))
        self.Mname.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Mname.setObjectName("Mname")
        self.verticalLayout_14.addWidget(self.Mname)
        self.horizontalLayout_4.addWidget(self.widget_8, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.widget_3 = QtWidgets.QWidget(self.upper)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Indicator = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Indicator.sizePolicy().hasHeightForWidth())
        self.Indicator.setSizePolicy(sizePolicy)
        self.Indicator.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Indicator.setObjectName("Indicator")
        self.verticalLayout_10.addWidget(self.Indicator, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.widget_3)
        self.verticalLayout_6.addWidget(self.upper)
        self.verticalLayout_3.addWidget(self.StaffNameCon, 0, QtCore.Qt.AlignTop)
        self.Specialization = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Specialization.sizePolicy().hasHeightForWidth())
        self.Specialization.setSizePolicy(sizePolicy)
        self.Specialization.setObjectName("Specialization")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Specialization)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Title_2 = QtWidgets.QLabel(self.Specialization)
        self.Title_2.setObjectName("Title_2")
        self.verticalLayout_8.addWidget(self.Title_2, 0, QtCore.Qt.AlignTop)
        self.widget_6 = QtWidgets.QWidget(self.Specialization)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 55))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_11 = QtWidgets.QWidget(self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9, 0, QtCore.Qt.AlignTop)
        self.License = QtWidgets.QLineEdit(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.License.sizePolicy().hasHeightForWidth())
        self.License.setSizePolicy(sizePolicy)
        self.License.setMinimumSize(QtCore.QSize(0, 35))
        self.License.setMaximumSize(QtCore.QSize(16777215, 35))
        self.License.setObjectName("License")
        self.verticalLayout_17.addWidget(self.License)
        self.horizontalLayout_6.addWidget(self.widget_11, 0, QtCore.Qt.AlignTop)
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8, 0, QtCore.Qt.AlignTop)
        self.Specialty = QtWidgets.QComboBox(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Specialty.sizePolicy().hasHeightForWidth())
        self.Specialty.setSizePolicy(sizePolicy)
        self.Specialty.setMinimumSize(QtCore.QSize(0, 35))
        self.Specialty.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Specialty.setObjectName("Specialty")
        self.verticalLayout_16.addWidget(self.Specialty)
        self.horizontalLayout_6.addWidget(self.widget_10, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_8.addWidget(self.widget_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.Specialization, 0, QtCore.Qt.AlignTop)
        self.StaffInfo = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StaffInfo.sizePolicy().hasHeightForWidth())
        self.StaffInfo.setSizePolicy(sizePolicy)
        self.StaffInfo.setObjectName("StaffInfo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.StaffInfo)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Title_3 = QtWidgets.QLabel(self.StaffInfo)
        self.Title_3.setObjectName("Title_3")
        self.verticalLayout_7.addWidget(self.Title_3)
        self.upper_2 = QtWidgets.QWidget(self.StaffInfo)
        self.upper_2.setMinimumSize(QtCore.QSize(0, 55))
        self.upper_2.setObjectName("upper_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.upper_2)
        self.horizontalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_16 = QtWidgets.QWidget(self.upper_2)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_14 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_22.addWidget(self.label_14)
        self.ID = QtWidgets.QLineEdit(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID.sizePolicy().hasHeightForWidth())
        self.ID.setSizePolicy(sizePolicy)
        self.ID.setMinimumSize(QtCore.QSize(0, 35))
        self.ID.setMaximumSize(QtCore.QSize(16777215, 35))
        self.ID.setObjectName("ID")
        self.verticalLayout_22.addWidget(self.ID)
        self.horizontalLayout_5.addWidget(self.widget_16)
        self.widget_14 = QtWidgets.QWidget(self.upper_2)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_20.addWidget(self.label_12, 0, QtCore.Qt.AlignTop)
        self.Gender = QtWidgets.QComboBox(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gender.sizePolicy().hasHeightForWidth())
        self.Gender.setSizePolicy(sizePolicy)
        self.Gender.setMinimumSize(QtCore.QSize(0, 35))
        self.Gender.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Gender.setObjectName("Gender")
        self.verticalLayout_20.addWidget(self.Gender)
        self.horizontalLayout_5.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.upper_2)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_21.addWidget(self.label_13, 0, QtCore.Qt.AlignTop)
        self.Dob = QtWidgets.QDateEdit(self.widget_15)
        self.Dob.setMinimumSize(QtCore.QSize(0, 35))
        self.Dob.setMaximumSize(QtCore.QSize(16777209, 35))
        self.Dob.setStyleSheet("color: black;")
        self.Dob.setCalendarPopup(True)
        self.Dob.setObjectName("Dob")
        self.verticalLayout_21.addWidget(self.Dob)
        self.horizontalLayout_5.addWidget(self.widget_15, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.upper_2, 0, QtCore.Qt.AlignTop)
        self.lower_2 = QtWidgets.QWidget(self.StaffInfo)
        self.lower_2.setMinimumSize(QtCore.QSize(0, 55))
        self.lower_2.setObjectName("lower_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.lower_2)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, -1)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.lower_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.Email = QtWidgets.QLineEdit(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Email.sizePolicy().hasHeightForWidth())
        self.Email.setSizePolicy(sizePolicy)
        self.Email.setMinimumSize(QtCore.QSize(0, 35))
        self.Email.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Email.setObjectName("Email")
        self.verticalLayout_15.addWidget(self.Email)
        self.horizontalLayout_8.addWidget(self.widget_9, 0, QtCore.Qt.AlignTop)
        self.widget_17 = QtWidgets.QWidget(self.lower_2)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_15 = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_23.addWidget(self.label_15, 0, QtCore.Qt.AlignTop)
        self.Address = QtWidgets.QLineEdit(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Address.sizePolicy().hasHeightForWidth())
        self.Address.setSizePolicy(sizePolicy)
        self.Address.setMinimumSize(QtCore.QSize(0, 35))
        self.Address.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Address.setObjectName("Address")
        self.verticalLayout_23.addWidget(self.Address)
        self.horizontalLayout_8.addWidget(self.widget_17, 0, QtCore.Qt.AlignTop)
        self.widget_18 = QtWidgets.QWidget(self.lower_2)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_16 = QtWidgets.QLabel(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_24.addWidget(self.label_16, 0, QtCore.Qt.AlignTop)
        self.Contact = QtWidgets.QLineEdit(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contact.sizePolicy().hasHeightForWidth())
        self.Contact.setSizePolicy(sizePolicy)
        self.Contact.setMinimumSize(QtCore.QSize(0, 35))
        self.Contact.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Contact.setObjectName("Contact")
        self.verticalLayout_24.addWidget(self.Contact)
        self.horizontalLayout_8.addWidget(self.widget_18, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.lower_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.StaffInfo, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.Body, 0, QtCore.Qt.AlignTop)
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setStyleSheet("*{\n"
"    text-align: center;\n"
"}")
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Cancel = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel.sizePolicy().hasHeightForWidth())
        self.Cancel.setSizePolicy(sizePolicy)
        self.Cancel.setMinimumSize(QtCore.QSize(200, 45))
        self.Cancel.setMaximumSize(QtCore.QSize(200, 45))
        self.Cancel.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"}")
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel, 0, QtCore.Qt.AlignHCenter)
        self.AddStaff = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddStaff.sizePolicy().hasHeightForWidth())
        self.AddStaff.setSizePolicy(sizePolicy)
        self.AddStaff.setMinimumSize(QtCore.QSize(200, 45))
        self.AddStaff.setMaximumSize(QtCore.QSize(200, 45))
        self.AddStaff.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"}")
        self.AddStaff.setObjectName("AddStaff")
        self.horizontalLayout_2.addWidget(self.AddStaff, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Buttons, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "COVHACHA DIAGNOSTIC SYSTEM"))
        self.Subheader.setText(_translate("MainWindow", "Staff Registration Form"))
        self.label.setText(_translate("MainWindow", "Date Joined"))
        self.label_2.setText(_translate("MainWindow", "Staff Type"))
        self.Title_1.setText(_translate("MainWindow", "Staff Name"))
        self.label_5.setText(_translate("MainWindow", "First Name"))
        self.label_3.setText(_translate("MainWindow", "Last Name"))
        self.label_4.setText(_translate("MainWindow", "Middle Name"))
        self.Indicator.setText(_translate("MainWindow", "Staff name already registered."))
        self.Title_2.setText(_translate("MainWindow", "Doctor Details"))
        self.label_9.setText(_translate("MainWindow", "License Number"))
        self.label_8.setText(_translate("MainWindow", "Specialty"))
        self.Title_3.setText(_translate("MainWindow", "General Information"))
        self.label_14.setText(_translate("MainWindow", "Staff ID"))
        self.label_12.setText(_translate("MainWindow", "Gender"))
        self.label_13.setText(_translate("MainWindow", "Date of Birth"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_15.setText(_translate("MainWindow", "Address"))
        self.label_16.setText(_translate("MainWindow", "Contact Number"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.AddStaff.setText(_translate("MainWindow", "Add Staff"))
import Images.resources
