# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor_LabResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 800)
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 20)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 10px 20px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 40px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 25px;\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2E6E65;\n"
"    font-size: 15px;\n"
"    color: #1b3b3a;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        self.Header.setStyleSheet("QLabel {\n"
"    font: bold 20pt \"Satoshi Black\";\n"
"    color: #2E6E65;\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"    text-align: center;\n"
"}\n"
"#Subheader {\n"
"    font: 500 14pt \"Satoshi Medium\";\n"
"    text-align: center;\n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Header)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.Header)
        self.Title.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.Title.setAlignment(QtCore.Qt.AlignLeading)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.Subheader = QtWidgets.QLabel(self.Header)
        self.Subheader.setAlignment(QtCore.Qt.AlignLeading)
        self.Subheader.setObjectName("Subheader")
        self.verticalLayout.addWidget(self.Subheader)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignVCenter)
        self.MainBody = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MainBody.setStyleSheet("#Info {\n"
"    background-color: #b5cecb;\n"
"     border: 1px solid #2E6E65;\n"
"    /*border-radius: 20px;*/\n"
"}\n"
"\n"
"#Label, #label, #label_3 {\n"
"    font-size: 15px;\n"
"    font-weight: 300;\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#Label, #PatName, #Status, #OtherLabel, #label, #label_2, #label_4 {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#Type {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#Info {\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"#PatRecord {\n"
"     border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"#LabReq {\n"
"    border: 1px solid #2E6E65;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"#BPLabel_2, #BPInfo_2,\n"
"#TempLabel_2, #TempInfo_2,\n"
"#WeightLabel_2, #WeightInfo_2,\n"
"#HeightLabel_2, #HeightInfo_2 {\n"
"    font-size: 17px;\n"
"    font-weight: 300;\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#DiagnoseButton {\n"
"    text-align: center;\n"
"}")
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_5.setContentsMargins(20, -1, 20, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.MainBody)
        self.scrollArea_3.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}\n"
"")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -267, 1115, 868))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_24.setContentsMargins(0, 10, 0, 5)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.Info = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Info.sizePolicy().hasHeightForWidth())
        self.Info.setSizePolicy(sizePolicy)
        self.Info.setStyleSheet("QLabel {\n"
"    font: 500 13pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"#PatName, #PatID, #PatDoB, #PatGender, #PatAge, #PatStatus, #CheckUpID {\n"
"    font: 900 16pt \"Satoshi\";\n"
"}")
        self.Info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Info.setObjectName("Info")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Info)
        self.horizontalLayout_2.setContentsMargins(0, 5, 20, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PatInfo = QtWidgets.QFrame(self.Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatInfo.sizePolicy().hasHeightForWidth())
        self.PatInfo.setSizePolicy(sizePolicy)
        self.PatInfo.setStyleSheet("QLabel {\n"
"    font: 500 13pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"#PatName, #PatID, #PatDoB, #PatGender, #PatAge, #PatStatus {\n"
"    font: 900 16pt \"Satoshi\";\n"
"}")
        self.PatInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatInfo.setObjectName("PatInfo")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.PatInfo)
        self.verticalLayout_20.setContentsMargins(20, 5, 0, 5)
        self.verticalLayout_20.setSpacing(10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget = QtWidgets.QWidget(self.PatInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Label.setObjectName("Label")
        self.verticalLayout_4.addWidget(self.Label)
        self.PatID = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatID.sizePolicy().hasHeightForWidth())
        self.PatID.setSizePolicy(sizePolicy)
        self.PatID.setMaximumSize(QtCore.QSize(300, 16777215))
        self.PatID.setObjectName("PatID")
        self.verticalLayout_4.addWidget(self.PatID)
        self.horizontalLayout_8.addWidget(self.widget)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Label_2 = QtWidgets.QLabel(self.PatInfo)
        self.Label_2.setObjectName("Label_2")
        self.verticalLayout_6.addWidget(self.Label_2)
        self.PatName = QtWidgets.QLabel(self.PatInfo)
        self.PatName.setObjectName("PatName")
        self.verticalLayout_6.addWidget(self.PatName)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.frame_9 = QtWidgets.QFrame(self.PatInfo)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PatDOB = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatDOB.sizePolicy().hasHeightForWidth())
        self.PatDOB.setSizePolicy(sizePolicy)
        self.PatDOB.setMinimumSize(QtCore.QSize(189, 0))
        self.PatDOB.setStyleSheet("")
        self.PatDOB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatDOB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatDOB.setObjectName("PatDOB")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.PatDOB)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_3 = QtWidgets.QLabel(self.PatDOB)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_18.addWidget(self.label_3)
        self.PatDoB = QtWidgets.QLabel(self.PatDOB)
        self.PatDoB.setObjectName("PatDoB")
        self.verticalLayout_18.addWidget(self.PatDoB)
        self.horizontalLayout_3.addWidget(self.PatDOB)
        self.Age = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Age.sizePolicy().hasHeightForWidth())
        self.Age.setSizePolicy(sizePolicy)
        self.Age.setStyleSheet("")
        self.Age.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Age.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Age.setObjectName("Age")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Age)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.Age)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.PatAge = QtWidgets.QLabel(self.Age)
        self.PatAge.setObjectName("PatAge")
        self.verticalLayout_16.addWidget(self.PatAge)
        self.horizontalLayout_3.addWidget(self.Age)
        self.PatAge_2 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatAge_2.sizePolicy().hasHeightForWidth())
        self.PatAge_2.setSizePolicy(sizePolicy)
        self.PatAge_2.setStyleSheet("")
        self.PatAge_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatAge_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatAge_2.setObjectName("PatAge_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.PatAge_2)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.PatAge_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.PatGender = QtWidgets.QLabel(self.PatAge_2)
        self.PatGender.setObjectName("PatGender")
        self.verticalLayout_19.addWidget(self.PatGender)
        self.horizontalLayout_3.addWidget(self.PatAge_2)
        self.verticalLayout_20.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.PatInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Status_2 = QtWidgets.QFrame(self.Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status_2.sizePolicy().hasHeightForWidth())
        self.Status_2.setSizePolicy(sizePolicy)
        self.Status_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Status_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Status_2.setObjectName("Status_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Status_2)
        self.verticalLayout_21.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.Type_2 = QtWidgets.QLabel(self.Status_2)
        self.Type_2.setObjectName("Type_2")
        self.verticalLayout_21.addWidget(self.Type_2)
        self.CheckUpID = QtWidgets.QLabel(self.Status_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckUpID.sizePolicy().hasHeightForWidth())
        self.CheckUpID.setSizePolicy(sizePolicy)
        self.CheckUpID.setAlignment(QtCore.Qt.AlignLeading)
        self.CheckUpID.setObjectName("CheckUpID")
        self.verticalLayout_21.addWidget(self.CheckUpID, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.Status_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Status = QtWidgets.QFrame(self.Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        self.Status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Status.setObjectName("Status")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.Status)
        self.verticalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_17.setSpacing(1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Type = QtWidgets.QLabel(self.Status)
        self.Type.setObjectName("Type")
        self.verticalLayout_17.addWidget(self.Type)
        self.PatStatus = QtWidgets.QLabel(self.Status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatStatus.sizePolicy().hasHeightForWidth())
        self.PatStatus.setSizePolicy(sizePolicy)
        self.PatStatus.setAlignment(QtCore.Qt.AlignLeading)
        self.PatStatus.setObjectName("PatStatus")
        self.verticalLayout_17.addWidget(self.PatStatus, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.Status, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_24.addWidget(self.Info)
        self.PatRecord = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatRecord.sizePolicy().hasHeightForWidth())
        self.PatRecord.setSizePolicy(sizePolicy)
        self.PatRecord.setStyleSheet("QLabel {\n"
"    \n"
"    font: 700 14pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}")
        self.PatRecord.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatRecord.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatRecord.setObjectName("PatRecord")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.PatRecord)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PatDetails = QtWidgets.QFrame(self.PatRecord)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatDetails.sizePolicy().hasHeightForWidth())
        self.PatDetails.setSizePolicy(sizePolicy)
        self.PatDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatDetails.setObjectName("PatDetails")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PatDetails)
        self.horizontalLayout_4.setContentsMargins(20, 10, 0, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.PatDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BPLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.BPLabel_2.setObjectName("BPLabel_2")
        self.verticalLayout_8.addWidget(self.BPLabel_2)
        self.TempLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.TempLabel_2.setObjectName("TempLabel_2")
        self.verticalLayout_8.addWidget(self.TempLabel_2)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.BloodPressure = QtWidgets.QLabel(self.frame_6)
        self.BloodPressure.setObjectName("BloodPressure")
        self.verticalLayout_9.addWidget(self.BloodPressure)
        self.Temperature = QtWidgets.QLabel(self.frame_6)
        self.Temperature.setObjectName("Temperature")
        self.verticalLayout_9.addWidget(self.Temperature)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.PatDetails)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.WeightLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.WeightLabel_2.setObjectName("WeightLabel_2")
        self.verticalLayout_10.addWidget(self.WeightLabel_2)
        self.HeightLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.HeightLabel_2.setObjectName("HeightLabel_2")
        self.verticalLayout_10.addWidget(self.HeightLabel_2)
        self.horizontalLayout_7.addWidget(self.frame_7, 0, QtCore.Qt.AlignLeft)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Weight = QtWidgets.QLabel(self.frame_8)
        self.Weight.setObjectName("Weight")
        self.verticalLayout_11.addWidget(self.Weight)
        self.Height = QtWidgets.QLabel(self.frame_8)
        self.Height.setObjectName("Height")
        self.verticalLayout_11.addWidget(self.Height)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_7.addWidget(self.PatDetails)
        self.verticalLayout_24.addWidget(self.PatRecord)
        self.LabReq = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabReq.sizePolicy().hasHeightForWidth())
        self.LabReq.setSizePolicy(sizePolicy)
        self.LabReq.setStyleSheet("#LabLabel, #DiagnoseLabel {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#BPLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#BPInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#AgeLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#AgeInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#GenderLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#GenderInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#WeightLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#WeightInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#HeightLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#HeightInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#TempLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#TempInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"\n"
"\n"
"#OtherText {\n"
"    border: none;\n"
"    border-bottom: 2px solid #2b3752;\n"
"    background: transparent;\n"
"    color: #2b3752;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"#DiagnoseText, #DiagnoseNotes {\n"
"    border: none;\n"
"    border-bottom: 1px solid black;\n"
"    background-color: transparent;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"\n"
"#ViewTestButton {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    border-bottom: 1px solid #3E7C75;\n"
"    color: #3E7C75;\n"
"    background-color: transparent;\n"
"    font: 20px \"Arial\";\n"
"    padding: 2px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"\n"
"")
        self.LabReq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LabReq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LabReq.setObjectName("LabReq")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.LabReq)
        self.verticalLayout_23.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout_23.setSpacing(15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.Header_2 = QtWidgets.QFrame(self.LabReq)
        self.Header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header_2.setObjectName("Header_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Header_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.LabLabel = QtWidgets.QLabel(self.Header_2)
        self.LabLabel.setObjectName("LabLabel")
        self.verticalLayout_13.addWidget(self.LabLabel, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.Header_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 953, 200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.LabTestTabe = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.LabTestTabe.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font:500 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 700 15pt \"Satoshi\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"")
        self.LabTestTabe.setObjectName("LabTestTabe")
        self.LabTestTabe.setColumnCount(2)
        self.LabTestTabe.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LabTestTabe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabTestTabe.setHorizontalHeaderItem(1, item)
        self.LabTestTabe.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_14.addWidget(self.LabTestTabe)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ViewLabResult = QtWidgets.QPushButton(self.widget_3)
        self.ViewLabResult.setObjectName("ViewLabResult")
        self.verticalLayout_3.addWidget(self.ViewLabResult)
        self.horizontalLayout_5.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.frame = QtWidgets.QFrame(self.Header_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 10, 10, 10)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DiagnoseLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiagnoseLabel.sizePolicy().hasHeightForWidth())
        self.DiagnoseLabel.setSizePolicy(sizePolicy)
        self.DiagnoseLabel.setObjectName("DiagnoseLabel")
        self.horizontalLayout_10.addWidget(self.DiagnoseLabel)
        self.DiagnoseText = QtWidgets.QLineEdit(self.frame)
        self.DiagnoseText.setObjectName("DiagnoseText")
        self.horizontalLayout_10.addWidget(self.DiagnoseText)
        self.verticalLayout_13.addWidget(self.frame)
        self.verticalLayout_23.addWidget(self.Header_2)
        self.frame_10 = QtWidgets.QFrame(self.LabReq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setContentsMargins(0, 10, 10, 20)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.DiagnoseLabel_2 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiagnoseLabel_2.sizePolicy().hasHeightForWidth())
        self.DiagnoseLabel_2.setSizePolicy(sizePolicy)
        self.DiagnoseLabel_2.setObjectName("DiagnoseLabel_2")
        self.horizontalLayout_11.addWidget(self.DiagnoseLabel_2)
        self.DiagnoseNotes = QtWidgets.QLineEdit(self.frame_10)
        self.DiagnoseNotes.setObjectName("DiagnoseNotes")
        self.horizontalLayout_11.addWidget(self.DiagnoseNotes)
        self.verticalLayout_23.addWidget(self.frame_10)
        self.label_2 = QtWidgets.QLabel(self.LabReq)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_23.addWidget(self.label_2)
        self.widget_4 = QtWidgets.QWidget(self.LabReq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_4)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 953, 200))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.LabTestTabe_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.LabTestTabe_2.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font:500 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 700 15pt \"Satoshi\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"")
        self.LabTestTabe_2.setObjectName("LabTestTabe_2")
        self.LabTestTabe_2.setColumnCount(3)
        self.LabTestTabe_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LabTestTabe_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabTestTabe_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabTestTabe_2.setHorizontalHeaderItem(2, item)
        self.LabTestTabe_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_22.addWidget(self.LabTestTabe_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_9.addWidget(self.scrollArea_2)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.AddPrescription = QtWidgets.QPushButton(self.widget_5)
        self.AddPrescription.setObjectName("AddPrescription")
        self.verticalLayout_12.addWidget(self.AddPrescription)
        self.EditPrescription = QtWidgets.QPushButton(self.widget_5)
        self.EditPrescription.setObjectName("EditPrescription")
        self.verticalLayout_12.addWidget(self.EditPrescription, 0, QtCore.Qt.AlignTop)
        self.DeletePrescription = QtWidgets.QPushButton(self.widget_5)
        self.DeletePrescription.setObjectName("DeletePrescription")
        self.verticalLayout_12.addWidget(self.DeletePrescription)
        self.horizontalLayout_9.addWidget(self.widget_5, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_23.addWidget(self.widget_4)
        self.verticalLayout_24.addWidget(self.LabReq)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_3)
        self.verticalLayout_2.addWidget(self.MainBody)
        self.Button = QtWidgets.QFrame(self.MainBodyContainer)
        self.Button.setStyleSheet("QPushButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"     padding: 10px 20px;\n"
"    text-align: center;\n"
"}")
        self.Button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Button.setObjectName("Button")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Button)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Cancel = QtWidgets.QPushButton(self.Button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel.sizePolicy().hasHeightForWidth())
        self.Cancel.setSizePolicy(sizePolicy)
        self.Cancel.setMinimumSize(QtCore.QSize(200, 60))
        self.Cancel.setMaximumSize(QtCore.QSize(200, 60))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ticket-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel.setIcon(icon)
        self.Cancel.setIconSize(QtCore.QSize(40, 40))
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_12.addWidget(self.Cancel)
        self.DiagnoseButton = QtWidgets.QPushButton(self.Button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiagnoseButton.sizePolicy().hasHeightForWidth())
        self.DiagnoseButton.setSizePolicy(sizePolicy)
        self.DiagnoseButton.setMinimumSize(QtCore.QSize(200, 60))
        self.DiagnoseButton.setMaximumSize(QtCore.QSize(200, 60))
        self.DiagnoseButton.setIcon(icon)
        self.DiagnoseButton.setIconSize(QtCore.QSize(40, 40))
        self.DiagnoseButton.setObjectName("DiagnoseButton")
        self.horizontalLayout_12.addWidget(self.DiagnoseButton)
        self.verticalLayout_2.addWidget(self.Button, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.MainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "COVHACHA DIAGNOSTIC SYSTEM"))
        self.Subheader.setText(_translate("MainWindow", "Patient Diagnose Form"))
        self.Label.setText(_translate("MainWindow", "Patient ID"))
        self.PatID.setText(_translate("MainWindow", "1000023"))
        self.Label_2.setText(_translate("MainWindow", "Patient Name"))
        self.PatName.setText(_translate("MainWindow", "Rondina, Roy Adrian"))
        self.label_3.setText(_translate("MainWindow", "Date of Birth"))
        self.PatDoB.setText(_translate("MainWindow", "12-23-23"))
        self.label.setText(_translate("MainWindow", "Age"))
        self.PatAge.setText(_translate("MainWindow", "20"))
        self.label_5.setText(_translate("MainWindow", "Gender"))
        self.PatGender.setText(_translate("MainWindow", "Male"))
        self.Type_2.setText(_translate("MainWindow", "Check-Up ID"))
        self.CheckUpID.setText(_translate("MainWindow", "121323-001"))
        self.Type.setText(_translate("MainWindow", "Check Up Type"))
        self.PatStatus.setText(_translate("MainWindow", "New Check Up"))
        self.BPLabel_2.setText(_translate("MainWindow", "Blood Pressure:"))
        self.TempLabel_2.setText(_translate("MainWindow", "Temperature: "))
        self.BloodPressure.setText(_translate("MainWindow", "120/90 bpm"))
        self.Temperature.setText(_translate("MainWindow", "98 C"))
        self.WeightLabel_2.setText(_translate("MainWindow", "Weight:"))
        self.HeightLabel_2.setText(_translate("MainWindow", "Height:"))
        self.Weight.setText(_translate("MainWindow", "30 kg"))
        self.Height.setText(_translate("MainWindow", "170 cm"))
        self.LabLabel.setText(_translate("MainWindow", "Laboratory Test Results "))
        item = self.LabTestTabe.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lab Test"))
        item = self.LabTestTabe.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Attachment"))
        self.ViewLabResult.setText(_translate("MainWindow", "View"))
        self.DiagnoseLabel.setText(_translate("MainWindow", "Diagnosis:  "))
        self.DiagnoseLabel_2.setText(_translate("MainWindow", "Notes:  "))
        self.label_2.setText(_translate("MainWindow", "Prescription"))
        item = self.LabTestTabe_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Medicine"))
        item = self.LabTestTabe_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dosage"))
        item = self.LabTestTabe_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Interval"))
        self.AddPrescription.setText(_translate("MainWindow", "Add"))
        self.EditPrescription.setText(_translate("MainWindow", "Edit"))
        self.DeletePrescription.setText(_translate("MainWindow", "Delete"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.DiagnoseButton.setText(_translate("MainWindow", "Diagnose"))
