# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_LabRequest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 821)
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 16pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.NavBarButton = QtWidgets.QPushButton(self.NavBar)
        self.NavBarButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lucide/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NavBarButton.setIcon(icon)
        self.NavBarButton.setIconSize(QtCore.QSize(40, 40))
        self.NavBarButton.setObjectName("NavBarButton")
        self.verticalLayout_12.addWidget(self.NavBarButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/lucide/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.verticalLayout_3.addWidget(self.DashboardButton)
        self.RecordsButton = QtWidgets.QPushButton(self.NavBar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/lucide/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordsButton.setIcon(icon2)
        self.RecordsButton.setIconSize(QtCore.QSize(40, 40))
        self.RecordsButton.setObjectName("RecordsButton")
        self.verticalLayout_3.addWidget(self.RecordsButton)
        self.TransactionButton = QtWidgets.QPushButton(self.NavBar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lucide/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionButton.setIcon(icon3)
        self.TransactionButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionButton.setObjectName("TransactionButton")
        self.verticalLayout_3.addWidget(self.TransactionButton)
        self.LabRequestButton = QtWidgets.QPushButton(self.NavBar)
        self.LabRequestButton.setStyleSheet("QPushButton {\n"
"    font: 900 20pt \"Satoshi Black\";\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lucide/icons/test-tubes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LabRequestButton.setIcon(icon4)
        self.LabRequestButton.setIconSize(QtCore.QSize(40, 40))
        self.LabRequestButton.setObjectName("LabRequestButton")
        self.verticalLayout_3.addWidget(self.LabRequestButton)
        self.verticalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 362, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.NavBar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.NavBar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/lucide/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.NavBar, 0, QtCore.Qt.AlignLeft)
        self.MainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 20px 20px;\n"
"    padding-bottom: 10px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 25px;\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2E6E65;\n"
"    font-size: 15px;\n"
"    color: #1b3b3a;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InterfaceTitle.setAlignment(QtCore.Qt.AlignLeading)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_2.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.ID = QtWidgets.QLabel(self.Header)
        self.ID.setObjectName("ID")
        self.UserInfo.addWidget(self.ID, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_5.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_2.addLayout(self.UserPanel)
        self.verticalLayout.addWidget(self.Header)
        self.Body = QtWidgets.QWidget(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("\n"
"QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #CCE3D0;\n"
"    color: #2E6E65;\n"
"}\n"
"")
        self.Body.setObjectName("Body")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("#SearchBar {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"#Search{\n"
"    background-color: transparent ;\n"
"    font: 300 14pt \"Lexend Light\";\n"
"}\n"
"#AddUserButton {\n"
"    text-align: center;\n"
"}\n"
"#Icon {\n"
"    background-color: transparent;\n"
"}\n"
"QComboBox {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/lucide/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SearchBar = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBar.sizePolicy().hasHeightForWidth())
        self.SearchBar.setSizePolicy(sizePolicy)
        self.SearchBar.setMinimumSize(QtCore.QSize(290, 0))
        self.SearchBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Icon = QtWidgets.QPushButton(self.SearchBar)
        self.Icon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/lucide/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon7)
        self.Icon.setIconSize(QtCore.QSize(30, 30))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_4.addWidget(self.Icon)
        self.Search = QtWidgets.QLineEdit(self.SearchBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search.sizePolicy().hasHeightForWidth())
        self.Search.setSizePolicy(sizePolicy)
        self.Search.setObjectName("Search")
        self.horizontalLayout_4.addWidget(self.Search)
        self.horizontalLayout_5.addWidget(self.SearchBar)
        self.Specialty = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Specialty.sizePolicy().hasHeightForWidth())
        self.Specialty.setSizePolicy(sizePolicy)
        self.Specialty.setMinimumSize(QtCore.QSize(0, 0))
        self.Specialty.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Specialty.setObjectName("Specialty")
        self.Specialty.addItem("")
        self.Specialty.addItem("")
        self.Specialty.addItem("")
        self.horizontalLayout_5.addWidget(self.Specialty)
        spacerItem2 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.Body)
        self.widget.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(20, 10, 20, 20)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 754, 644))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LabRequestTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.LabRequestTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"")
        self.LabRequestTable.setColumnCount(4)
        self.LabRequestTable.setObjectName("LabRequestTable")
        self.LabRequestTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LabRequestTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabRequestTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabRequestTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabRequestTable.setHorizontalHeaderItem(3, item)
        self.LabRequestTable.horizontalHeader().setSortIndicatorShown(False)
        self.LabRequestTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.LabRequestTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Modify = QtWidgets.QPushButton(self.widget_2)
        self.Modify.setObjectName("Modify")
        self.verticalLayout_2.addWidget(self.Modify)
        self.Delete = QtWidgets.QPushButton(self.widget_2)
        self.Delete.setObjectName("Delete")
        self.verticalLayout_2.addWidget(self.Delete)
        self.horizontalLayout_3.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.widget)
        self.verticalLayout.addWidget(self.Body)
        self.horizontalLayout.addWidget(self.MainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DashboardButton.setText(_translate("MainWindow", " Dashboard"))
        self.RecordsButton.setText(_translate("MainWindow", " Records"))
        self.TransactionButton.setText(_translate("MainWindow", " Transactions"))
        self.LabRequestButton.setText(_translate("MainWindow", " Lab Request"))
        self.pushButton_9.setText(_translate("MainWindow", "Profile"))
        self.pushButton_10.setText(_translate("MainWindow", "Logout"))
        self.InterfaceTitle.setText(_translate("MainWindow", "Lab Request"))
        self.UserName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.ID.setText(_translate("MainWindow", "Staff"))
        self.Specialty.setItemText(0, _translate("MainWindow", "Gynecologist"))
        self.Specialty.setItemText(1, _translate("MainWindow", "Pediatrician"))
        self.Specialty.setItemText(2, _translate("MainWindow", "Opthalmologist"))
        item = self.LabRequestTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Check-Up ID"))
        item = self.LabRequestTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.LabRequestTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Doctor"))
        item = self.LabRequestTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        self.Modify.setText(_translate("MainWindow", "Modify"))
        self.Delete.setText(_translate("MainWindow", "Delete"))
