# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_AddLabAttachment.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 536)
        MainWindow.setBaseSize(QtCore.QSize(800, 640))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"    background-color: #F4F7ED;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setStyleSheet("QLabel {\n"
"    font: bold 20pt \"Satoshi Black\";\n"
"    color: #2E6E65;\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"#Subheader {\n"
"    font: 500 14pt \"Satoshi Medium\";\n"
"}")
        self.Header.setObjectName("Header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Header)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QLabel(self.Header)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.Title)
        self.Subheader = QtWidgets.QLabel(self.Header)
        self.Subheader.setAlignment(QtCore.Qt.AlignCenter)
        self.Subheader.setObjectName("Subheader")
        self.verticalLayout_2.addWidget(self.Subheader)
        self.verticalLayout.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QLabel {\n"
"    font: 300 12pt \"Lexend Light\";\n"
"    color: #2E6E65;\n"
"}\n"
"#Patient, #Doctor {\n"
"    font: 14pt \"Lexend SemiBold\";\n"
"}\n"
"#StaffTypeCon, #StaffNameCon, #StaffInfoCon, #SpecializationCon {\n"
"    background-color: transparent;\n"
"}\n"
"*{\n"
"    background-color: transparent;\n"
"}\n"
"#Body {\n"
"    background-color: rgba(46, 110, 101, 77);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.Body.setObjectName("Body")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.Body)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Title_2 = QtWidgets.QLabel(self.widget_5)
        self.Title_2.setObjectName("Title_2")
        self.verticalLayout_3.addWidget(self.Title_2)
        self.Patient = QtWidgets.QLabel(self.widget_5)
        self.Patient.setObjectName("Patient")
        self.verticalLayout_3.addWidget(self.Patient)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.Doctor = QtWidgets.QLabel(self.widget_6)
        self.Doctor.setObjectName("Doctor")
        self.verticalLayout_4.addWidget(self.Doctor)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.Body)
        self.widget_4.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_4.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.Body)
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Cancel = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel.sizePolicy().hasHeightForWidth())
        self.Cancel.setSizePolicy(sizePolicy)
        self.Cancel.setMinimumSize(QtCore.QSize(200, 45))
        self.Cancel.setMaximumSize(QtCore.QSize(200, 45))
        self.Cancel.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"}")
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.AddCheckUp = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddCheckUp.sizePolicy().hasHeightForWidth())
        self.AddCheckUp.setSizePolicy(sizePolicy)
        self.AddCheckUp.setMinimumSize(QtCore.QSize(200, 45))
        self.AddCheckUp.setMaximumSize(QtCore.QSize(200, 45))
        self.AddCheckUp.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"}")
        self.AddCheckUp.setObjectName("AddCheckUp")
        self.horizontalLayout_2.addWidget(self.AddCheckUp)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Buttons, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "COVHACHA DIAGNOSTIC SYSTEM"))
        self.Subheader.setText(_translate("MainWindow", "Lab Result Attachment Form"))
        self.Title_2.setText(_translate("MainWindow", "Patient Name"))
        self.Patient.setText(_translate("MainWindow", "Roy Adrian"))
        self.label_3.setText(_translate("MainWindow", "Requested By"))
        self.Doctor.setText(_translate("MainWindow", "Jayson Limosnero"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lab Test Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Attachment"))
        self.pushButton.setText(_translate("MainWindow", "View"))
        self.pushButton_2.setText(_translate("MainWindow", "Attach"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.AddCheckUp.setText(_translate("MainWindow", "Update"))
import resources_rc
