# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_TransactionProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 16pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"#User, #UserSpecialty {\n"
"    color: #F4F7ED;\n"
"}\n"
"#DoctorSidePanel {\n"
"     background-color: #2E6E65;\n"
"}\n"
"\n"
"#RecentText {\n"
"    color: #F4F7ED;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DashBoardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashBoardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lucide/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashBoardButton.setIcon(icon)
        self.DashBoardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashBoardButton.setObjectName("DashBoardButton")
        self.verticalLayout.addWidget(self.DashBoardButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.pushButton_3 = QtWidgets.QPushButton(self.NavBar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/lucide/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.MainButtons.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.NavBar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/lucide/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.MainButtons.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.NavBar)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lucide/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.MainButtons.addWidget(self.pushButton)
        self.pushButton_7 = QtWidgets.QPushButton(self.NavBar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lucide/icons/test-tubes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.MainButtons.addWidget(self.pushButton_7)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.NavBar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.NavBar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/lucide/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 20px 20px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"}\n"
"#UserType {\n"
"    font: 500 13pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 900 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 25px;\n"
"    background: white;\n"
"}\n"
"\n"
"#label_45 {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"")
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_17 = QtWidgets.QWidget(self.Header)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #2E6E65;\n"
"}")
        self.pushButton_6.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/lucide/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon7)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignVCenter)
        self.widget_16 = QtWidgets.QWidget(self.widget_17)
        self.widget_16.setStyleSheet("#label {\n"
"    font: 500 12pt \"Satoshi\";\n"
"}\n"
"#InterfaceTitle {\n"
"    font-size: 24px;\n"
"}")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label = QtWidgets.QLabel(self.widget_16)
        self.label.setObjectName("label")
        self.verticalLayout_27.addWidget(self.label)
        self.InterfaceTitle = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceTitle.sizePolicy().hasHeightForWidth())
        self.InterfaceTitle.setSizePolicy(sizePolicy)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.verticalLayout_27.addWidget(self.InterfaceTitle)
        self.horizontalLayout_2.addWidget(self.widget_16, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_8.addWidget(self.widget_17, 0, QtCore.Qt.AlignTop)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setSpacing(10)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_6.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_8.addLayout(self.UserPanel)
        self.verticalLayout_3.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.MainBody = QtWidgets.QWidget(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setStyleSheet("#label_2, #label_4, #label_6,  #label_8, #label_11, #label_13, #label_17, #label_18, #label_21, #label_23,  #label_25, #label_26, #label_38, #label_39, #label_40, #label_41 {\n"
"    color: #2b3752;\n"
"    font: 500 13pt \"Satoshi\";\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #2b3752;\n"
"}\n"
"#Doc, #Pat, #Lab, #Transact {\n"
"    color: #2E6E65;\n"
"    font-size: 22px ;\n"
"}\n"
"#widget, #PatientInfo, #DoctorInfo, #SummaryFrame {\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#frame_5 {\n"
"    background-color: #2e6e65;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"#label_29, #label_30, #label_31 {\n"
"    color: #F4F7ED;\n"
"}\n"
"\n"
"#frame_6, #frame_7 {\n"
"    background-color: #b9cec4;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"#CancelButton, #CompleteButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"")
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_4.setContentsMargins(15, 0, 15, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.MainBody)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(20, 15, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Transact = QtWidgets.QLabel(self.widget)
        self.Transact.setObjectName("Transact")
        self.verticalLayout_5.addWidget(self.Transact)
        self.TransactionInfos = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TransactionInfos.sizePolicy().hasHeightForWidth())
        self.TransactionInfos.setSizePolicy(sizePolicy)
        self.TransactionInfos.setStyleSheet("")
        self.TransactionInfos.setObjectName("TransactionInfos")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TransactionInfos)
        self.horizontalLayout_3.setContentsMargins(0, 0, 20, 10)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.TransactionInfos)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.TransactionID = QtWidgets.QLabel(self.widget_2)
        self.TransactionID.setObjectName("TransactionID")
        self.verticalLayout_7.addWidget(self.TransactionID)
        self.horizontalLayout_3.addWidget(self.widget_2, 0, QtCore.Qt.AlignLeft)
        self.widget_3 = QtWidgets.QWidget(self.TransactionInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.Diagnosis = QtWidgets.QLabel(self.widget_3)
        self.Diagnosis.setObjectName("Diagnosis")
        self.verticalLayout_8.addWidget(self.Diagnosis)
        self.horizontalLayout_3.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(self.TransactionInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.DiagnosisNotes = QtWidgets.QLabel(self.widget_4)
        self.DiagnosisNotes.setObjectName("DiagnosisNotes")
        self.verticalLayout_9.addWidget(self.DiagnosisNotes)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.TransactionInfos)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.DoctorCharge = QtWidgets.QLabel(self.widget_5)
        self.DoctorCharge.setObjectName("DoctorCharge")
        self.verticalLayout_10.addWidget(self.DoctorCharge)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.TransactionInfos, 0, QtCore.Qt.AlignTop)
        self.MainTransaction = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTransaction.sizePolicy().hasHeightForWidth())
        self.MainTransaction.setSizePolicy(sizePolicy)
        self.MainTransaction.setObjectName("MainTransaction")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.MainTransaction)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.MainTransaction)
        self.widget_8.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Pat = QtWidgets.QLabel(self.widget_8)
        self.Pat.setObjectName("Pat")
        self.verticalLayout_11.addWidget(self.Pat)
        self.PatientInfo = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatientInfo.sizePolicy().hasHeightForWidth())
        self.PatientInfo.setSizePolicy(sizePolicy)
        self.PatientInfo.setObjectName("PatientInfo")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.PatientInfo)
        self.verticalLayout_24.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_24.setSpacing(15)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_11 = QtWidgets.QWidget(self.PatientInfo)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.PatID = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatID.sizePolicy().hasHeightForWidth())
        self.PatID.setSizePolicy(sizePolicy)
        self.PatID.setObjectName("PatID")
        self.verticalLayout_12.addWidget(self.PatID)
        self.verticalLayout_24.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.PatientInfo)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_23.setSpacing(1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_13 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_23.addWidget(self.label_13)
        self.PatName = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatName.sizePolicy().hasHeightForWidth())
        self.PatName.setSizePolicy(sizePolicy)
        self.PatName.setObjectName("PatName")
        self.verticalLayout_23.addWidget(self.PatName)
        self.verticalLayout_24.addWidget(self.widget_12)
        self.widget_9 = QtWidgets.QWidget(self.PatientInfo)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.PatGender = QtWidgets.QLabel(self.frame)
        self.PatGender.setObjectName("PatGender")
        self.verticalLayout_16.addWidget(self.PatGender)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_17.addWidget(self.label_23)
        self.PatAge = QtWidgets.QLabel(self.frame_2)
        self.PatAge.setObjectName("PatAge")
        self.verticalLayout_17.addWidget(self.PatAge)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_24.addWidget(self.widget_9)
        self.verticalLayout_11.addWidget(self.PatientInfo)
        self.Doc = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Doc.sizePolicy().hasHeightForWidth())
        self.Doc.setSizePolicy(sizePolicy)
        self.Doc.setObjectName("Doc")
        self.verticalLayout_11.addWidget(self.Doc)
        self.DoctorInfo = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoctorInfo.sizePolicy().hasHeightForWidth())
        self.DoctorInfo.setSizePolicy(sizePolicy)
        self.DoctorInfo.setObjectName("DoctorInfo")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.DoctorInfo)
        self.verticalLayout_25.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_25.setSpacing(15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_13 = QtWidgets.QWidget(self.DoctorInfo)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.widget_13)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        self.DocID = QtWidgets.QLabel(self.widget_13)
        self.DocID.setObjectName("DocID")
        self.verticalLayout_15.addWidget(self.DocID)
        self.verticalLayout_25.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.DoctorInfo)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.widget_14)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.DocName = QtWidgets.QLabel(self.widget_14)
        self.DocName.setObjectName("DocName")
        self.verticalLayout_19.addWidget(self.DocName)
        self.verticalLayout_25.addWidget(self.widget_14)
        self.widget_10 = QtWidgets.QWidget(self.DoctorInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.widget_10)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_18.addWidget(self.label_25)
        self.DocSpecialty = QtWidgets.QLabel(self.frame_4)
        self.DocSpecialty.setObjectName("DocSpecialty")
        self.verticalLayout_18.addWidget(self.DocSpecialty)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_25.addWidget(self.widget_10)
        self.verticalLayout_11.addWidget(self.DoctorInfo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.widget_6 = QtWidgets.QWidget(self.MainTransaction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_13.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Lab = QtWidgets.QLabel(self.widget_6)
        self.Lab.setObjectName("Lab")
        self.verticalLayout_13.addWidget(self.Lab, 0, QtCore.Qt.AlignTop)
        self.SummaryFrame = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SummaryFrame.sizePolicy().hasHeightForWidth())
        self.SummaryFrame.setSizePolicy(sizePolicy)
        self.SummaryFrame.setMinimumSize(QtCore.QSize(0, 300))
        self.SummaryFrame.setObjectName("SummaryFrame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.SummaryFrame)
        self.verticalLayout_26.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_26.setSpacing(5)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.scrollArea = QtWidgets.QScrollArea(self.SummaryFrame)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 560, 245))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.LabChargeTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.LabChargeTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font:500 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    font: 700 15pt \"Satoshi\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.LabChargeTable.setObjectName("LabChargeTable")
        self.LabChargeTable.setColumnCount(2)
        self.LabChargeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LabChargeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LabChargeTable.setHorizontalHeaderItem(1, item)
        self.LabChargeTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_14.addWidget(self.LabChargeTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_26.addWidget(self.scrollArea)
        self.widget_15 = QtWidgets.QWidget(self.SummaryFrame)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_26 = QtWidgets.QLabel(self.widget_15)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_7.addWidget(self.label_26, 0, QtCore.Qt.AlignVCenter)
        self.OtherFees = QtWidgets.QLineEdit(self.widget_15)
        self.OtherFees.setMinimumSize(QtCore.QSize(0, 30))
        self.OtherFees.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border-bottom: 2px solid #2E6E65;\n"
"    font: 900 14pt \"Satoshi Black\";\n"
"}")
        self.OtherFees.setObjectName("OtherFees")
        self.horizontalLayout_7.addWidget(self.OtherFees)
        self.verticalLayout_26.addWidget(self.widget_15)
        self.verticalLayout_13.addWidget(self.SummaryFrame)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 17)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.widget_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_38 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.DiscountSelection = QtWidgets.QComboBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiscountSelection.sizePolicy().hasHeightForWidth())
        self.DiscountSelection.setSizePolicy(sizePolicy)
        self.DiscountSelection.setMinimumSize(QtCore.QSize(150, 0))
        self.DiscountSelection.setObjectName("DiscountSelection")
        self.DiscountSelection.addItem("")
        self.verticalLayout_20.addWidget(self.DiscountSelection)
        self.horizontalLayout_10.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.widget_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_39 = QtWidgets.QLabel(self.frame_10)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_21.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.frame_10)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_21.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.frame_10)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_21.addWidget(self.label_41)
        self.horizontalLayout_11.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.SubtotalAmount = QtWidgets.QLabel(self.frame_11)
        self.SubtotalAmount.setObjectName("SubtotalAmount")
        self.verticalLayout_22.addWidget(self.SubtotalAmount, 0, QtCore.Qt.AlignRight)
        self.DiscountedAmount = QtWidgets.QLabel(self.frame_11)
        self.DiscountedAmount.setObjectName("DiscountedAmount")
        self.verticalLayout_22.addWidget(self.DiscountedAmount, 0, QtCore.Qt.AlignRight)
        self.TotalAmount = QtWidgets.QLabel(self.frame_11)
        self.TotalAmount.setObjectName("TotalAmount")
        self.verticalLayout_22.addWidget(self.TotalAmount, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_11.addWidget(self.frame_11)
        self.horizontalLayout_10.addWidget(self.frame_9)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.horizontalLayout_4.addWidget(self.widget_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.MainTransaction, 0, QtCore.Qt.AlignTop)
        self.frame_12 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CompleteButton = QtWidgets.QPushButton(self.frame_12)
        self.CompleteButton.setMinimumSize(QtCore.QSize(200, 60))
        self.CompleteButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.CompleteButton.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"}")
        self.CompleteButton.setObjectName("CompleteButton")
        self.horizontalLayout_12.addWidget(self.CompleteButton)
        self.verticalLayout_5.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.MainBody, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.MainBodyContainer, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", " Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", " Records"))
        self.pushButton.setText(_translate("MainWindow", " Transactions"))
        self.pushButton_7.setText(_translate("MainWindow", " Lab Request"))
        self.pushButton_5.setText(_translate("MainWindow", " Settings"))
        self.pushButton_4.setText(_translate("MainWindow", " Logout"))
        self.label.setText(_translate("MainWindow", "Back to Transaction List"))
        self.InterfaceTitle.setText(_translate("MainWindow", "Process Transaction"))
        self.UserName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("MainWindow", "Nurse"))
        self.Transact.setText(_translate("MainWindow", "Transaction Details"))
        self.label_2.setText(_translate("MainWindow", "Transaction ID"))
        self.TransactionID.setText(_translate("MainWindow", "121224-001"))
        self.label_4.setText(_translate("MainWindow", "Diagnosis"))
        self.Diagnosis.setText(_translate("MainWindow", "Fever"))
        self.label_6.setText(_translate("MainWindow", "Diagnosis Notes"))
        self.DiagnosisNotes.setText(_translate("MainWindow", "...."))
        self.label_8.setText(_translate("MainWindow", "Base Charge"))
        self.DoctorCharge.setText(_translate("MainWindow", "₱ 00"))
        self.Pat.setText(_translate("MainWindow", "Patient\'s Info"))
        self.label_11.setText(_translate("MainWindow", "Patient ID"))
        self.PatID.setText(_translate("MainWindow", "100000001"))
        self.label_13.setText(_translate("MainWindow", "Patient Name"))
        self.PatName.setText(_translate("MainWindow", "Jayson Gabriel L. Limosnero"))
        self.label_21.setText(_translate("MainWindow", "Gender"))
        self.PatGender.setText(_translate("MainWindow", "Male"))
        self.label_23.setText(_translate("MainWindow", "Age"))
        self.PatAge.setText(_translate("MainWindow", "24"))
        self.Doc.setText(_translate("MainWindow", "Doctor\'s Info"))
        self.label_17.setText(_translate("MainWindow", "Doctor ID"))
        self.DocID.setText(_translate("MainWindow", "D-100003"))
        self.label_18.setText(_translate("MainWindow", "Doctor Name"))
        self.DocName.setText(_translate("MainWindow", "Roy Adrian R. Rondina"))
        self.label_25.setText(_translate("MainWindow", "Specialty"))
        self.DocSpecialty.setText(_translate("MainWindow", "Ophthalmologist"))
        self.Lab.setText(_translate("MainWindow", "Diagnostic Charges Summary"))
        item = self.LabChargeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Laboratory Test"))
        item = self.LabChargeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Charge"))
        self.label_26.setText(_translate("MainWindow", "Other Fees:"))
        self.OtherFees.setText(_translate("MainWindow", "50"))
        self.label_38.setText(_translate("MainWindow", "Discounts"))
        self.DiscountSelection.setItemText(0, _translate("MainWindow", "Seniors"))
        self.label_39.setText(_translate("MainWindow", "Subtotal:"))
        self.label_40.setText(_translate("MainWindow", "Discount Deduction:"))
        self.label_41.setText(_translate("MainWindow", "Total:"))
        self.SubtotalAmount.setText(_translate("MainWindow", "₱ 00.00"))
        self.DiscountedAmount.setText(_translate("MainWindow", "-₱ 00.00"))
        self.TotalAmount.setText(_translate("MainWindow", "₱ 00.00"))
        self.CompleteButton.setText(_translate("MainWindow", "Complete"))
import Images.resources
